spring:
  datasource:
    url: jdbc:mysql://139.196.89.233:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hxj123.
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  type-aliases-package: com.itheima.mp.domian.po
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: albertzhao@albertzhao.cn
    concat: albertzhao
    url: http://127.0.0.1:8888/doc.html
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources: com.itheima.mp.controller
server:
  port: 8888